#ifndef QWEBVIEW2_VERSION_H_
#define QWEBVIEW2_VERSION_H_
#pragma once

#ifndef QWEBVIEW2_VERSION_MAJOR
#define QWEBVIEW2_VERSION_MAJOR 1
#define QWEBVIEW2_VERSION_MINOR 0
#define QWEBVIEW2_VERSION_PATCH 4
#endif

#endif // !QWEBVIEW2_VERSION_H_
